config/routes.rb
Rails.application.routes.draw do
  
  resources "students"

    root 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
	validates :name, :presence => true
	validates :student_class, :presence => true
	validates :marks, :presence => true
	validates :description, :presence => true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :current_student, only: [:show, :edit, :update , :destroy]

  def index
    @students = Student.all
  end

  def show
    #@student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to root_path
    else
      render "new"  
    end  
  end

  def edit

  end

  def update
    if @student.update(student_params)
      redirect_to students_path
    else
      render students_edit_path
    end  
  end

  def destroy
    if @student.destroy
      redirect_to students_path
    end
  end

  private
  
  def current_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :student_class, :marks , :description)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%=  simple_form_for @student do |f| %>
<%= f.error_notification %>
	<%= f.input :name %>
	<%= f.input :student_class, label: "class" %>
	<%= f.input :marks  %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>
<%= render "form" %>
<%= link_to "back", students_path %>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>
<%= @students.find_each do |student| %>
	<table>
		<tr>
			<th>Student Names</th>
		</tr>
		<tr>
			<td><%= student.name %></td>
			<td><%= link_to "show", student_path(student) %></td>
		</tr>
			
	</table>	
<% end %>
<%= link_to "Add Student", new_student_path, class: "button" %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render "form" %>
<%= link_to "back", students_path %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>
<h2><%= @student.name %></h2>
<p><b>Class:</b><%= @student.student_class %></p>
<p><b>Marks:</b><%= @student.marks %></p>
<p><b>Description:</b><%= @student.description %></p>
<%= link_to "delete", student_path(@student), method: :delete, data: { confirm: "Are sure want to delete" } %>
<%= link_to "edit", edit_student_path(@student) %>
<%= link_to "back", students_path %>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>